services:
  web_portafolio:
    build: .
    container_name: web_portafolio
    command: sh -c "python manage.py migrate && gunicorn --bind 0.0.0.0:8000 Portafolio.wsgi:application"
    volumes:
      - .:/web
    environment:
      - DEBUG=0
      - DATABASE_URL=<database-url>
    ports:
      - "8000:8000"
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
