services:
  web_portafolio:
    build:
      context: .
    container_name: web_portafolio
    command: sh -c "python manage.py migrate --noinput && gunicorn --bind 0.0.0.0:8000 Portafolio.wsgi:application"
    volumes:
      - .:/web
      - static_volume:/web/static
      - media_volume:/web/media
    environment:
      - DEBUG=0
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "8000:8000"

    depends_on:
      - db
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  static_volume:
  media_volume:
