services:
  web_portafolio:
  build:
    context: .
    container_name: web_portafolio
    command: sh -c "python manage.py migrate --noinput && gunicorn --bind 0.0.0.0:8000 Portafolio.wsgi:application"
    volumes:
      - .:/web
      - ./media:/web_portafolio/media
    networks:
      - webnet
    environment:
      - DEBUG=0
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "8000:8000"

    depends_on:
      - db
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - webnet
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./media:/web_portafolio/media
    networks:
      - webnet
    ports:
      - "80:80"
    depends_on:
      - web_portafolio

volumes:
  postgres_data:
  media_volume:
networks:
  webnet:
    driver: bridge
