services:
  web_portafolio:
    build: .
    container_name: web_portafolio
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/web
      - sqlite_data:/web/db_data
    environment:
      - DEBUG=0
    ports:
      - "8000:8000"
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_data:/web/staticfiles
      - media_data:/web/media
    depends_on:
      - web_portafolio
    networks:
      - app_network

volumes:
  static_data:
  media_data:
  sqlite_data:

networks:
  app_network:
    driver: bridge
